version: 1
formatters:
  formatter_1:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%m-%d-%Y %H:%M:%S %Z"
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/datetimep.log
    when: 'M'
    interval: 2
    backupCount: 3
    encoding: utf8
    formatter: formatter_1
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: formatter_1
loggers:
  datetimep:
    level: INFO
    propogation: yes
    handlers: [file]