version: 1
formatters:
  formatter_1:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%m-%d-%Y %H:%M:%S %Z"
handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: ./logs/study.log
    when: 'D'
    interval: 1
    backupCount: 10
    encoding: utf8
    formatter: formatter_1
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: formatter_1
loggers:
  datetimep:
    level: DEBUG
    propogation: yes
    handlers: [file]
  study.exception:
    level: DEBUG
    propogation: yes
    handlers: [file]
  study.fileStudy:
    level: DEBUG
    propogation: yes
    handlers: [file]
  study.webRequestStudy:
    level: DEBUG
    propogation: yes
    handlers: [file]
  